# Generated by Django 5.0.7 on 2025-08-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_docs/')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('scan', 'Scan/Imaging'), ('discharge', 'Discharge Summary'), ('other', 'Others')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.profile')),
            ],
        ),
    ]
