# Generated by Django 5.0.7 on 2025-08-31 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_date_of_birth'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='profile',
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vault_password', models.CharField(max_length=255)),
                ('qr_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.vault'),
        ),
    ]
