# Generated by Django 5.0.7 on 2025-08-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ocr_uploads')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_result', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_uploads', to='accounts.profile')),
            ],
        ),
    ]
